jax_seed: 0 # seed
num_epochs: 100 # number of training epochs
num_iters: 1  # number of deer iterations
method: 'seq'  # 'deer' ,'seq'
learning_rate: 0.001  # learning rate
hidden_size: 16  # hidden size

debug: false # debug mode

use_wandb: true  # use wandb for logging
wandb_project: "gru_seq_mnist"  # wandb project name"

early_stopping: true  # early stopping
early_stopping_metric: "val_loss"  # early stopping metric
early_stopping_patience: 5  # early stopping patience
early_stopping_min_delta: 0.0001  # early stopping min delta


dataset: "mnist-classification"
dir_name: "."
batch_size: 16  # batch size


