# default params from: https://arxiv.org/pdf/1710.02224
jax_seed: 0 # seed
num_epochs: 100 # number of training epochs
num_iters: 2  # number of deer iterations
method: 'quasideer'  # 'quasideer', 'deer' ,'seq'
k: 0. # amount of damping, should be between 0 and 1. Should be the strenght of damping, so that 0 is no damping, and 1 is max damping. Usually around 0.05 is good
learning_rate: 0.001  # learning rate
hidden_size: 32  # hidden size

debug: false # debug mode

use_wandb: false # use wandb for logging
#wandb_project: "deer_gru_mnist"  # wandb project name"
wandb_project: "deer_minrnn_mnist"  # wandb project name"

early_stopping: true  # early stopping
early_stopping_metric: "val_loss"  # early stopping metric
early_stopping_patience: 5  # early stopping patience
early_stopping_min_delta: 0.0001  # early stopping min delta


dataset: "mnist-classification"
dir_name: "data"
batch_size: 16  # batch size


