# gru default params from: https://arxiv.org/pdf/1710.02224
# minrrn default params from: 
seed: 0 # seed
num_epochs: 100 # number of training epochs
num_iters: 784  # number of deer iterations, serves as the max if using while loop!!
method: 'quasideer'  # 'quasideer', 'deer' ,'seq', 'picard'
k: 0. # amount of damping, should be between 0 and 1. Should be the strength of damping, so that 0 is no damping, and 1 is max damping. Usually around 0.05 is good
clip: False  # use clip ELK
learning_rate: 0.001  # learning rate
hidden_size: 256  # hidden size
model_type: "gru"
while_loop: True  # use while loop

tol: 1e-4  # tolerance for convergence

debug: false # debug mode

use_wandb: wandb # use wandb for logging
wandb_project: "nonlinear_ssm"

early_stopping: true  # early stopping
early_stopping_metric: "val_loss"  # early stopping metric
early_stopping_patience: 10  # early stopping patience
early_stopping_min_delta: 0.0001  # early stopping min delta


dataset: "mnist-classification"
dir_name: "data"
batch_size: 256  # batch size, need to run with batch_size 64 for DEER

fast_dev_run: False
explore: False # if explore is True, don't use hold out test set

date: "2025-01-28"

hydra:
  run:
    dir: .


